services:
  - type: web
    name: clipper-laravel
    runtime: php
    region: frankfurt
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize
    startCommand: |
      php artisan migrate --force
      apache2-foreground # Render uses Apache for PHP by default
    envVars:
      - key: APP_KEY
        sync: false 
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql